version: '3'

services:
  redis:
    image: "redislabs/redismod:edge"
    ports:
      - "6379:6379"
    links:
      - "es:es"
  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
        - discovery.type=single-node
  insight:
    image: "redislabs/redisinsight:latest"
    ports:
      - "8001:8001"
    depends_on:
      - redis
